services:
  - type: web
    name: lucky-draw
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    build:
      environment:
        PYTHON_VERSION: 3.11.9
